mysql -userguser -ptopsecret -e "USE QA; INSERT auth_user(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES(1,'0','2010-10-10',0,'auth1','auth1','auth1','afsfasdas',0,0,'2010-10-10');"
mysql -userguser -ptopsecret -e "USE QA; INSERT auth_user(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES(2,'0','2010-10-10',0,'auth2','auth2','auth2','afsfasdas',0,0,'2010-10-10');"
mysql -userguser -ptopsecret -e "USE QA; INSERT auth_user(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES(3,'0','2010-10-10',0,'auth3','auth3','auth3','afsfasdas',0,0,'2010-10-10');"
mysql -userguser -ptopsecret -e "USE QA; INSERT auth_user(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES(4,'0','2010-10-10',0,'auth4','auth4','auth4','afsfasdas',0,0,'2010-10-10');"
mysql -userguser -ptopsecret -e "USE QA; INSERT auth_user(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES(5,'0','2010-10-10',0,'auth5','auth5','auth5','afsfasdas',0,0,'2010-10-10');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('1','title1','text1','2012-5-24','4','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('2','title2','text2','2013-7-11','8','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('3','title3','text3','2012-9-23','8','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('4','title4','text4','2013-7-19','1','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('5','title5','text5','2012-8-16','4','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('6','title6','text6','2011-2-19','8','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('7','title7','text7','2011-7-18','1','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('8','title8','text8','2013-7-15','0','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('9','title9','text9','2012-5-11','5','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('10','title10','text10','2013-1-18','0','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('11','title11','text11','2011-8-19','2','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('12','title12','text12','2011-7-11','7','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('13','title13','text13','2012-4-13','7','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('14','title14','text14','2012-5-20','0','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('15','title15','text15','2012-3-19','1','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('16','title16','text16','2013-2-23','3','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('17','title17','text17','2012-4-17','8','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('18','title18','text18','2011-5-13','8','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('19','title19','text19','2013-5-15','0','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('20','title20','text20','2013-9-24','4','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('21','title21','text21','2012-5-14','7','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('22','title22','text22','2012-2-24','6','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('23','title23','text23','2011-3-14','0','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('24','title24','text24','2011-9-17','9','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('25','title25','text25','2013-2-17','1','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('26','title26','text26','2012-6-24','1','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('27','title27','text27','2012-6-15','8','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('28','title28','text28','2012-1-15','3','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('29','title29','text29','2012-9-19','0','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('30','title30','text30','2011-3-18','4','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('31','title31','text31','2012-8-17','3','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('32','title32','text32','2011-3-18','8','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('33','title33','text33','2012-3-15','6','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('34','title34','text34','2011-3-19','6','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('35','title35','text35','2012-4-16','1','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('36','title36','text36','2012-9-24','1','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('37','title37','text37','2013-1-15','5','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('38','title38','text38','2012-2-14','1','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('39','title39','text39','2012-8-12','3','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('40','title40','text40','2013-7-11','4','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('41','title41','text41','2012-6-16','9','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('42','title42','text42','2011-5-14','8','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('43','title43','text43','2011-1-22','1','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('44','title44','text44','2011-4-15','1','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('45','title45','text45','2012-1-16','0','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('46','title46','text46','2013-7-16','7','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('47','title47','text47','2011-2-14','4','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('48','title48','text48','2013-2-16','5','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('49','title49','text49','2012-6-23','3','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_question(id, title, text, added_at, rating, author_id) VALUES('50','title50','text50','2013-1-19','4','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-2-24','1','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-5-16','2','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-3-24','3','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-8-24','3','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-4-13','4','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-7-12','5','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-7-19','6','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-7-18','7','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-8-12','7','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2015-2-16','7','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-3-13','8','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-9-22','8','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-9-13','9','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-1-17','9','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2014-9-18','9','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-4-22','10','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-5-15','10','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2014-8-14','10','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-2-18','11','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-2-12','12','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-5-22','12','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2015-2-24','12','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-9-18','13','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-1-20','14','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-3-22','14','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2014-9-11','14','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-1-17','15','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-3-21','15','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2015-8-14','15','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-2-13','16','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-4-22','17','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-2-16','17','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-8-24','18','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-3-19','18','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2015-8-12','18','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-5-13','19','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-4-15','19','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-1-24','20','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-2-19','21','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-6-15','21','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2014-4-23','21','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-6-16','22','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-8-15','23','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-6-20','24','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-4-22','25','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-7-16','26','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-8-14','26','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2015-9-22','26','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-5-18','27','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-6-11','28','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-8-14','29','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-9-11','29','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-3-21','30','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-6-16','30','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-4-15','31','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-5-18','31','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2014-9-19','31','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-7-22','32','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-6-22','32','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2014-5-24','32','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-8-22','33','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-6-19','33','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-5-14','34','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-3-21','34','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-9-16','35','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-4-18','36','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-9-21','37','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-3-21','37','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2014-5-15','37','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-8-15','38','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-8-20','38','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2015-9-19','38','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-7-19','39','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-3-24','40','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-8-20','40','1');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-6-12','41','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-9-15','42','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-2-23','43','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-7-24','43','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-3-13','44','2');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-7-16','44','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2014-8-19','44','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-8-16','45','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-3-17','45','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-4-18','46','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-1-23','46','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2015-2-20','46','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-1-11','47','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-6-18','47','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-2-22','48','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2015-5-18','48','5');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer3','2015-7-14','48','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2015-8-22','49','4');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer1','2014-3-11','50','3');"
mysql -userguser -ptopsecret -e "USE QA; INSERT qa_answer(text, added_at, question_id, author_id) VALUES('answer2','2014-5-21','50','5');"
